services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5675:5672"
      - "15675:15672"

  app1:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - IS_WORKER=0
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq

  app2:
    build: .
    environment:
      - IS_WORKER=1
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq
