services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5675:5672"
      - "15675:15672"

  app1:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - IS_WORKER=0
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq

  app2:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - IS_WORKER=1
      - WORKERS_COUNT=${WORKERS_COUNT}
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq
